// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://agkuipulmkmibbjxyhsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFna3VpcHVsbWttaWJianh5aHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODA0MTQsImV4cCI6MjA2MTM1NjQxNH0.xQalHBnf9v2xuk3hKoQk6FWjCE8lX6p-4c2jleX88GQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});